require_relative "sw_characters/version"
require_relative './sw_characters/cli.rb'
require_relative './sw_characters/character.rb'
require_relative './sw_characters/api.rb'
require_relative './sw_characters/planet.rb'
require_relative './sw_characters/film.rb'
require_relative './sw_characters/species.rb'
require 'open-uri'
require 'nokogiri'
